trigger:
  branches:
    include:
      - refs/heads/main
      - refs/tags/v*
pr: 
  - main

pool:
  vmImage: 'Ubuntu 16.04'

stages:
- stage: Test
  jobs:
  - job: test_lists
    steps:
    - script: make test
      displayName: 'Test Package Lists'
